export default [
  {
    path: '/guias/visa-americana-familias/', label: 'Visa americana en familia',
    title: 'Visa americana en familia desde Paraguay | Guía',
    description: 'Cómo preparar la solicitud de visa B1/B2 si viajás con pareja e hijos: un DS-160 por persona, fotos de menores, cita y respuestas coherentes.',
    h1: 'Visa americana en familia: cada persona tiene su propia solicitud',
    lead: 'Cuando viaja una familia completa, es fácil pensar que alcanza con una sola carpeta. No es así: cada integrante, incluidos los menores, tiene su propia solicitud. Esta guía informativa te ayuda a organizar los datos para que todo cuente la misma historia.',
    inline: { label: 'Contanos cómo viaja tu familia', href: '/contacto/', body: 'Esta guía es informativa. Si tenés dudas sobre cómo organizar la información de varios viajeros, escribinos y vemos qué conviene consultar en las fuentes oficiales.' },
    parts: [
      ['un-formulario-por-persona', 'Un DS-160 por cada viajero, también los menores', [
        'El DS-160 es el formulario en línea de la solicitud de visa y se completa de forma individual. Eso incluye a los bebés y a los niños: cada menor tiene su propio formulario, con su propio número de confirmación. No existe un formulario familiar que reemplace a los demás, aunque todos viajen juntos y compartan domicilio. Revisá cada ficha con calma antes de enviarla, porque una vez presentada ya no es tan sencillo modificarla.',
        'Antes de empezar, juntá los pasaportes vigentes de todos los viajeros y anotá los datos de cada uno tal como figuran en el documento. Si alguien todavía no tiene pasaporte, ese es el primer paso pendiente. Conviene que la información básica de la familia, como el domicilio y los datos de contacto, se copie sin cambios de una persona a la otra. Tené a mano las actas de nacimiento de los menores, ya que a veces hace falta confirmar nombres, apellidos y vínculos con los adultos que los acompañan.',
      ]],
      ['menores-y-firma', 'Quién completa y firma por un menor', [
        'Los menores no pueden responder el formulario por su cuenta. Lo habitual es que un padre, una madre o un tutor complete las preguntas en su nombre, con la información real del niño o la niña. Quien lo hace asume la responsabilidad de que lo declarado sea verdadero, igual que si fuera su propia solicitud. Es un trámite que merece un rato tranquilo, sin apuro, para que los datos del niño sean tan cuidados como los de los adultos.',
        'Si el menor viaja con uno solo de sus padres, o con otro adulto, pensá desde temprano qué documentos de familia podrían ser pertinentes y quién puede acreditar la relación. Las exigencias de salida del país y de asistencia a la entrevista tienen reglas propias que pueden cambiar. Consultá las instrucciones vigentes en travel.state.gov y en los canales oficiales de Paraguay. Si hay un adulto que todavía no sabe bien cómo se organiza el viaje, conviene que lo converse con el resto antes de responder, para no contradecir a nadie.',
      ]],
      ['fotos-de-ninos', 'Fotos de bebés y niños', [
        'La foto del DS-160 tiene condiciones precisas de encuadre, fondo y expresión, y también se aplican a los menores. Con los más chicos suele ser lo más difícil: se mueven, miran hacia otro lado o cambian el gesto. Elegí un momento de calma, con buena luz pareja y sin objetos en el fondo, y no dejes la foto para el último día. Una buena práctica es sacar las fotos de los niños en la casa, con paciencia, y probar varias veces hasta lograr una imagen que cumpla las pautas oficiales sin esfuerzo.',
        'Leé las especificaciones oficiales de la foto en travel.state.gov antes de sacarla, incluidas las indicaciones para bebés y niños pequeños. Si la imagen no cumple, el sistema puede rechazarla o puede generar demoras. Es más práctico tomar varias fotos de cada niño y elegir con tranquilidad cuál se ajusta mejor, sin retocarlas ni editarlas. No retoques la imagen con filtros ni aplicaciones, porque eso puede hacer que el sistema la rechace.',
      ]],
      ['cita-en-conjunto', 'Agendar la cita para toda la familia', [
        'El pago y la cita se gestionan por el sistema oficial de citas, y cada solicitante tiene su propio perfil. Cuando la familia viaja junta, conviene intentar que las citas queden el mismo día y en el mismo horario, aunque la disponibilidad real de turnos dependa del sistema y no siempre permita esa coincidencia. Nadie puede asegurar un día determinado. Por eso conviene empezar a mirar fechas con anticipación y no dejar el trámite para cuando el viaje ya está comprado.',
        'Antes de agendar, confirmá que los datos de cada perfil coincidan con el pasaporte y con el DS-160 de esa persona. Un error de nombre o de fecha de nacimiento se vuelve más difícil de corregir después. Guardá los comprobantes de cada integrante en un mismo lugar, ordenados por persona, para tenerlos a mano el día de la entrevista. Si las fechas de los turnos quedan distintas, consultá las opciones del sistema oficial antes de modificar nada por tu cuenta.',
      ]],
      ['coherencia', 'Respuestas coherentes entre familiares', [
        'Los datos compartidos deberían ser iguales en todos los formularios: domicilio, motivo del viaje, fechas, lugar donde se alojarían y quién paga cada gasto. Si una persona dice que viajan por quince días y otra por un mes, o si el empleo de un adulto figura de manera distinta, aparece una inconsistencia que cuesta explicar. Antes de enviar, compará los formularios entre sí. Un buen ejercicio es sentarse juntos, leer cada respuesta en voz alta y marcar las diferencias, para corregirlas con el dato correcto antes de presentar los formularios.',
        'La coherencia no significa memorizar un guion. Significa que todos conozcan el plan real: adónde van, cuánto tiempo, con quién se quedan y cómo se financia el viaje. Si los padres pagan, que lo expliquen así; si ayuda otro familiar, que se diga con claridad. La decisión final corresponde siempre a la autoridad consular, y esta guía no promete ningún resultado. Consultá en las fuentes oficiales qué se espera de los menores el día de la cita, porque esas reglas pueden variar según la edad y la situación.',
      ]],
    ],
  },
  {
    path: '/guias/visa-americana-comerciantes-empresarios/', label: 'Visa americana para comerciantes',
    title: 'Visa americana para comerciantes y empresarios',
    description: 'B1 o B2, cómo explicar tu negocio con claridad y qué información muestra tus vínculos con Paraguay si sos comerciante o trabajás por cuenta propia.',
    h1: 'Visa americana para comerciantes, empresarios y trabajadores independientes',
    lead: 'Si tenés un comercio, una empresa o trabajás por cuenta propia, tu viaje puede mezclar compras, reuniones y paseo. Esta guía informativa explica cómo distinguir los motivos, cómo contar tu actividad con palabras simples y qué información ayuda a entender tu situación.',
    inline: { label: 'Contanos qué tipo de viaje planeás', href: '/contacto/', body: 'Esta guía es informativa. Si no tenés claro si tu viaje es de negocios, de turismo o ambos, escribinos y te contamos qué fuentes oficiales conviene leer.' },
    parts: [
      ['b1-o-b2', 'B1 y B2: qué cubre cada una', [
        'La visa de visitante se solicita habitualmente en conjunto como B1/B2. La B1 corresponde a actividades de negocios de corta duración, como reuniones, contactos con proveedores o ferias. La B2 corresponde al turismo, la visita a familiares o el descanso. Qué categoría se aplica depende del motivo concreto de tu viaje, que debe ser verdadero. Leer la definición oficial de cada categoría ayuda a no elegir por costumbre ni por lo que hizo un conocido.',
        'Esa visa no autoriza a trabajar ni a recibir un pago por servicios dentro de Estados Unidos. Tampoco sirve para instalarte allá con tu negocio. Si tu plan incluye algo distinto de una visita, por ejemplo abrir una empresa o prestar servicios a clientes locales, esa situación se evalúa con otras reglas. Consultá travel.state.gov antes de seguir. Si el viaje es solo de compras para tu propio comercio, preguntate cómo describirías esa actividad ante alguien que no conoce tu rubro.',
      ]],
      ['explicar-el-negocio', 'Explicá tu negocio en pocas palabras', [
        'En la entrevista, la persona que te atiende dispone de poco tiempo. Prepará una explicación breve y verdadera: qué vendés o qué servicio prestás, a quiénes, desde cuándo y cómo se organiza tu día de trabajo. No hace falta usar términos técnicos ni inflar la escala del negocio. Una descripción simple suele entenderse mejor que una complicada. Practicar la explicación en voz alta, con alguien de confianza, te permite notar qué partes suenan confusas y reformularlas sin inventar nada.',
        'Tené claro también cómo funciona tu actividad cuando vos no estás. Si tenés empleados, un socio o un familiar que se encarga del local durante tu viaje, eso forma parte de la explicación. Si trabajás solo, decilo con naturalidad. Lo importante es que lo que contés coincida con lo que figura en tu DS-160 y con lo que podrías mostrar. Si tu actividad cambió en los últimos años, contá esa evolución con naturalidad, porque el relato entero tiene que ser coherente con los datos que cargaste.',
      ]],
      ['vinculos-y-documentos', 'Información que muestra tu vida en Paraguay', [
        'Un comerciante o una persona independiente a veces no tiene recibo de sueldo, y eso genera dudas sobre cómo comprobar ingresos. No existe una lista fija obligatoria de papeles: cada caso es distinto. Pensá qué información describe de forma real tu actividad, como registros del negocio, constancias de tus obligaciones o movimientos habituales, y llevá solo lo que puedas explicar. Lo que elijas llevar debería responder a una pregunta concreta, por ejemplo cuánto hace que funciona tu actividad o cómo se sostiene tu familia.',
        'Tus vínculos con Paraguay pueden incluir el negocio, la familia, los estudios de tus hijos o una vivienda, según tu realidad. No se trata de reunir la mayor cantidad de documentos ni de aparentar lo que no tenés. Un papel que no entendés o que no coincide con tus respuestas puede generar más preguntas que respuestas. Tampoco tenés que armar un expediente grande: lo esencial es que cada dato que menciones tenga un respaldo real y que puedas contarlo sin confundirte.',
      ]],
      ['no-mezclar-motivos', 'No mezclar motivos sin explicarlo', [
        'Mucha gente combina una feria o una compra con unos días de paseo, y eso puede ser perfectamente legítimo. El problema aparece cuando el DS-160 dice una cosa y en la entrevista se cuenta otra, o cuando el viaje parece de turismo pero se habla de negocios recién al final. Elegí cómo presentar el motivo principal y mantenelo igual. Una forma de ordenar las ideas es escribir en dos líneas el objetivo principal del viaje y dejar lo demás como actividades secundarias.',
        'Si tu viaje tiene una parte laboral y otra de descanso, explicá el orden y la duración de cada una con naturalidad. Mencioná fechas aproximadas, lugares y con quién te reunirías, si ya lo sabés. Evitá afirmar que tenés reuniones confirmadas si todavía no las tenés. Decir qué está definido y qué no es parte de ser claro. Esa claridad también se nota en el DS-160, donde el propósito del viaje se declara por escrito y luego se compara con lo que decís en persona.',
      ]],
      ['financiacion-y-regreso', 'Financiación del viaje y plan de regreso', [
        'Pensá cómo vas a pagar los gastos del viaje: pasajes, alojamiento, compras y traslados. Si el dinero sale del negocio, explicá qué parte y por qué. Si te ayuda un familiar o un socio, indicalo tal cual. Mezclar el dinero personal con el de la empresa sin poder explicarlo es una de las situaciones que más cuesta aclarar durante una entrevista. Anotá las cifras con las que estés seguro y no inventes montos aproximados que después no podrías sostener si te piden un detalle.',
        'Tené presente que la autoridad consular evalúa cada solicitud por separado, y ningún conjunto de documentos asegura un resultado. Tu preparación debería enfocarse en comprender tu propio caso y poder describirlo con tranquilidad. Si la visa es negada, leé con atención los motivos informados, y considerá si realmente cambió algo importante antes de volver a solicitar. Lo recomendable es mantener la calma, responder lo que se pregunta y recordar que decir la verdad sin adornos es más importante que sonar perfecto.',
      ]],
    ],
  },
  {
    path: '/guias/visa-americana-tratamiento-medico/', label: 'Visa americana por tratamiento médico',
    title: 'Visa americana por tratamiento médico | Guía',
    description: 'Qué conviene poder explicar si viajás a Estados Unidos por un tratamiento médico con visa B1/B2: centro, financiación, duración y acompañante.',
    h1: 'Visa americana para un tratamiento médico: qué conviene poder explicar',
    lead: 'Viajar para atenderse en Estados Unidos puede hacerse con una visa B1/B2, y es un momento cargado de preocupaciones. Esta guía informativa no da consejos médicos ni legales: solo ordena las preguntas que suelen surgir sobre el centro, el pago, la estadía y quién te acompaña.',
    inline: { label: 'Escribinos si necesitás orientación general', href: '/contacto/', body: 'Esta guía es informativa y no reemplaza la opinión de tu equipo médico ni las instrucciones oficiales. Si querés saber qué fuentes consultar, contanos tu situación general.' },
    parts: [
      ['motivo-medico', 'El motivo médico como motivo de viaje', [
        'Un tratamiento puede ser el motivo de una solicitud de visa B1/B2, y debe declararse tal como es. Al completar el DS-160 y al conversar en la entrevista, lo importante es describir con sinceridad qué atención buscás, por qué querés recibirla en Estados Unidos y desde cuándo lo venís considerando. No hace falta dar detalles clínicos innecesarios. Contá tu situación de forma simple, y recordá que el DS-160 también pide datos de salud en algunas preguntas, que deben responderse con verdad.',
        'Cada persona decide cuánta información de salud comparte, y la autoridad consular puede hacer preguntas. Pensá de antemano cómo explicar tu situación con tus propias palabras, sin tecnicismos. Esta guía no evalúa si un tratamiento corresponde o no, ni da una opinión médica: esas decisiones son de tu equipo de salud, y la visa depende de la autoridad consular. Si hay algo que no entendés del diagnóstico o del plan, preguntalo primero a tu médico y recién después pensá cómo explicarlo en el trámite.',
      ]],
      ['centro-y-medico', 'El centro de salud y el profesional que te atenderá', [
        'Es útil poder decir en qué centro o con qué profesional te atenderías, en qué ciudad queda y cómo llegaste a ese contacto. Si fue por recomendación de tu médico en Paraguay, por una derivación o por una consulta que hiciste por tu cuenta, contalo tal cual sucedió. Un plan que se puede describir con detalle resulta más fácil de comprender. Guardá una copia de esa carta junto con tus otros papeles y leela completa, para poder contar qué dice si te preguntan por ella cuando la autoridad consular te consulte sobre tu viaje.',
        'Muchas personas cuentan con una carta del médico tratante o del centro de salud que describe la atención prevista y las fechas estimadas. No hay una lista obligatoria de papeles ni un formato único, y una carta no define el resultado. Si la carta está en otro idioma, consultá cómo presentarla de forma comprensible y asegurate de entender lo que dice. Podés pedir la carta con anticipación y consultar si el centro suele emitir ese tipo de documento, ya que no todos lo hacen de la misma manera.',
      ]],
      ['quien-paga', 'Quién paga y cómo se financia', [
        'Una de las preguntas más frecuentes es cómo se cubrirán los gastos: la atención, el alojamiento, los traslados y la alimentación. Pensá con claridad qué parte pagarías vos, qué parte un familiar y si hay algún seguro o cobertura que intervenga. Describí la financiación real, sin presentar ayuda de terceros como ingreso propio. Anotá cada fuente de dinero y quién se compromete a cada gasto, para que el relato sea el mismo en todos los formularios de la familia.',
        'Si el centro entregó un presupuesto o una estimación, conviene entender qué incluye y qué no. Pedí aclaraciones al propio centro sobre cualquier punto que no entiendas, y evitá repetir cifras de memoria si no estás segura de ellas. Esta guía no calcula costos ni recomienda instituciones: su objetivo es ayudarte a pensar la explicación completa. Hablar con el centro sobre formas de pago y plazos puede aclarar muchas dudas, pero esa conversación no reemplaza lo que decida la autoridad consular.',
      ]],
      ['estadia-y-acompanante', 'Duración de la estadía y acompañante', [
        'La duración prevista también se pregunta. Es normal que un tratamiento no tenga una fecha de fin exacta, y está bien decirlo con honestidad: contá cuánto tiempo estimás, qué podría extender o acortar la estadía y dónde te alojarías. Evitá inventar una duración precisa solo para que el plan parezca más ordenado. Pensá también en dónde se hospedarían ambos y cómo se trasladarían hasta el centro, porque son detalles que suelen surgir en la conversación.',
        'Si viajás con un acompañante, por ejemplo un familiar que te asiste durante el tratamiento, explicá quién es y por qué viaja con vos. Esa persona completa su propia solicitud, con su propio DS-160, y sus respuestas deben coincidir con las tuyas. Pensá también en cómo se organiza su vida y la tuya en Paraguay mientras estén afuera. Si es posible, hablá con tu equipo médico sobre un calendario aproximado, y recordá que cualquier cambio de fechas puede explicarse con naturalidad.',
      ]],
      ['entrevista-y-limites', 'La entrevista, los plazos y lo que nadie puede asegurar', [
        'La entrevista se realiza en la Embajada de los Estados Unidos en Asunción. Algunos casos pueden pedir un turno prioritario según las reglas vigentes de la embajada; consultá la información oficial sobre cómo solicitarlo. Ningún sitio privado puede conseguirte ese turno ni asegurar un resultado, y conviene desconfiar de quien lo ofrezca. Si necesitás entender mejor cómo funciona el proceso, la página oficial de la embajada y travel.state.gov son las fuentes de referencia para consultar.',
        'visas.com.py es un sitio privado e independiente que publica información, no es la embajada ni forma parte de ningún gobierno. No damos orientación médica ni jurídica. Si tenés dudas sobre tu salud, hablá con tu médico; si necesitás asesoramiento profesional sobre tu situación personal, consultá a un profesional matriculado, y para el trámite, a las fuentes oficiales. Leé la información oficial, escribinos si querés saber qué mirar primero, y recordá que la decisión sobre tu solicitud es siempre de la autoridad consular.',
      ]],
    ],
  },
];
