const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require(process.env.VISAS_PLAYWRIGHT_MODULE || 'playwright');
const root=path.resolve(__dirname,'..');
const site=process.env.VISAS_PREVIEW_URL || 'http://127.0.0.1:8787',out=path.join(root,'test-results/browser');fs.mkdirSync(out,{recursive:true});
async function main(){assert(['127.0.0.1','localhost'].includes(new URL(site).hostname),'Browser tests must stay local');const b=await chromium.launch({headless:true,...(process.env.VISAS_BROWSER_EXECUTABLE ? {executablePath:process.env.VISAS_BROWSER_EXECUTABLE} : {})});const c=await b.newContext();const errors=[];const report={routes:[],views:[],checks:[],metadataChanges:[]};
 const sm=await c.request.get(site+'/sitemap.xml');const routes=[...(await sm.text()).matchAll(/<loc>https:\/\/visas.com.py(.*?)<\/loc>/g)].map(m=>m[1]);
 const live=JSON.parse(fs.readFileSync(path.join(root,'docs/live-audit-2026-10-04.json')));
 for(const route of routes){const r=await c.request.get(site+route);assert.equal(r.status(),200,route);const html=await r.text();assert(!/name="robots" content="noindex/.test(html),route);assert.equal(html.match(/rel="canonical" href="(.*?)"/)?.[1],'https://visas.com.py'+route);for(const m of html.matchAll(/<script type="application\/ld\+json">(.*?)<\/script>/gs))JSON.parse(m[1]);const old=live.find(p=>p.url==='https://visas.com.py'+route);if(old){for(const [key,re]of [['title',/<title>(.*?)<\/title>/s],['h1',/<h1[^>]*>(.*?)<\/h1>/s],['canonical',/rel="canonical" href="(.*?)"/]])if(old[key]!==html.match(re)?.[1])report.metadataChanges.push({route,key,before:old[key],after:html.match(re)?.[1]});}report.routes.push({route,status:r.status()});}
 for(const route of ['/missing-preview-page/','/lib/leads.php','/docs/report.md','/content-refresh.mjs','/assets/img/manifest.json']){const r=await c.request.get(site+route);assert.equal(r.status(),404,route);}
 for(const [from,to]of [['/index.html','/'],['/visa-americana','/visa-americana/']]){const r=await c.request.get(site+from,{maxRedirects:0});assert.equal(r.status(),301);assert.equal(r.headers().location,to);}
 const pages=['/','/visa-americana/','/visa-canada/','/visa-espana/','/contacto/','/preguntas-frecuentes/','/guias/como-llenar-el-ds-160/','/privacidad/','/en/contact/'];
 for(const width of [390,1440]){const p=await c.newPage();await p.setViewportSize({width,height:width===390?844:1000});p.on('pageerror',e=>errors.push(e.message));for(const route of pages){await p.goto(site+route,{waitUntil:'networkidle'});await p.evaluate(()=>document.fonts.ready);await p.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=600){scrollTo(0,y);await new Promise(r=>setTimeout(r,50));}scrollTo(0,0);await Promise.all([...document.images].map(i=>{i.loading="eager";return i.decode().catch(()=>{});}));});const overflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert(!overflow,route+' overflow at '+width);assert.equal(await p.locator('h1').count(),1);const broken=await p.locator('img').evaluateAll(imgs=>imgs.filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src));assert.deepEqual(broken,[],route+' images');const stem=route==='/'?'home':route.replaceAll('/','-').replace(/^-|-$/g,'');await p.screenshot({path:path.join(out,stem+'-'+width+'.png'),fullPage:true});if(route==='/')await p.screenshot({path:path.join(out,'home-'+width+'-top.png')});report.views.push({route,width,overflow,images:'loaded'});console.log('PASS view',width,route);}await p.close();}
 const p=await c.newPage();await p.setViewportSize({width:390,height:844});await p.goto(site+'/');await p.locator('.burger').click();assert(await p.locator('#mobile-menu').evaluate(e=>e.open));await p.keyboard.press('Escape');assert(!(await p.locator('#mobile-menu').evaluate(e=>e.open)));assert(await p.locator('.burger').evaluate(e=>e===document.activeElement));report.checks.push('Mobile menu opens, Escape closes, focus returns');await p.locator('.mobile-wa [data-wa-trigger]').click();assert(await p.locator('#wa-menu').evaluate(e=>e.open));const options=await p.locator('[data-wa-option]').evaluateAll(a=>a.map(e=>e.href));assert(options.every(h=>h.startsWith('https://wa.me/595995628862?text=')));await p.keyboard.press('Escape');report.checks.push('WhatsApp chooser and seven valid links; no messages sent');
 await p.goto(site+'/contacto/');const sent=[];p.on('request',r=>{if(r.method()==='POST')sent.push(r.url());});await p.locator('#enquiry-destination').selectOption({label:'Canadá'});await p.locator('#enquiry-stage').selectOption({label:'Primera solicitud'});const target=new URL(await p.locator('[data-enquiry-link]').getAttribute('href'));assert(target.searchParams.get('text').includes('Canadá'));assert(target.searchParams.get('text').includes('Primera solicitud'));assert.deepEqual(sent,[]);assert.equal(await p.locator('input[type=file]').count(),0);assert.equal(await p.locator('#contact-form').count(),0);report.checks.push('Message helper encodes selected destination/topic without POST or document collection');
 await p.goto(site+'/en/contact/');await p.locator('#enquiry-destination').selectOption({label:'Canada'});assert((await p.locator('[data-enquiry-preview]').textContent()).includes('Destination: Canada'));report.checks.push('English message helper');
 for(const width of [320,768]){await p.setViewportSize({width,height:900});for(const route of ['/','/contacto/','/visa-americana/']){await p.goto(site+route);assert(!(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth)),route+' '+width);}}report.checks.push('Additional 320 and 768 px overflow checks');
 await p.goto(site+'/?audit_text=200');await p.setViewportSize({width:1440,height:1000});assert(!(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth)),'200% text overflow');report.checks.push('200% text scaling');
 await p.emulateMedia({reducedMotion:'reduce'});await p.goto(site+'/');assert.equal(await p.locator('.is-pending').count(),0);report.checks.push('Reduced motion');
 const nojs=await b.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const np=await nojs.newPage();await np.goto(site+'/contacto/');assert((await np.locator('[data-enquiry-link]').getAttribute('href')).startsWith('https://wa.me/'));report.checks.push('Contact fallback with JavaScript disabled');
 assert.deepEqual(errors,[]);report.checks.push('No browser JavaScript errors');fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));await b.close();console.log('PASS',report.routes.length,'routes',report.views.length,'screenshots',report.checks.length,'interaction checks');}
main().catch(e=>{console.error(e);process.exit(1)});
